name : docker, ci/cd, ec2, hub

on:
  push:
    branches:
      -dev

jobs:
  docker-cicd:
    runs-on: ubuntu-lastest
    steps:
      # 소스코드 체크 아웃
      # jdk17 설치
      # 필요시 현재까지 환경 수시 확인 가능    
      # 환경변수 동적 세팅 X
      # 빌드, 단위테스트 -> 편의상 개발자 pc에서 (프,백)선행실행
      # 도커 ㅇ관련 액션 -> 도커 작업을 위한 환경
      # 도커 허브 로그인 -> 계정정보 -> 시크릿 변수
      # 백엔드, 프론트 이미지 생성 -> 허브(레퍼지토리 푸시)
      # ec2 서버로 필요 파일 업로드 (YML, nginx/*.conf)