name : docker, ci/cd, ec2, hub

on:
  push:
    branches:
      - dev

jobs:
  docker-cicd:
    runs-on: ubuntu-latest
    steps:
      # 소스코드 체크 아웃ccc
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4
      # jdk17 설치
      - name: jdk 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      # 필요시 현재까지 환경 수시 확인 가능
      - name: 현재 상황 체크
        run: | 
          pwd
          ls    
      # 환경변수 동적 세팅 X
      # 빌드, 단위테스트 -> 편의상 개발자 pc에서 (프,백)선행실행

      # 도커 관련 액션 -> 도커 작업을 위한 환경
      - name: 도커 작업을 진행하기 위한 액션 적용
        uses: docker/setup-buildx-action@v3
        # 도커 허브 -> 프로필 -> 엑세스 토큰 발급

      # 도커 허브 로그인 -> 계정정보 -> 시크릿 변수
      - name: 도커 허브 로그인
        run: echo "${{secrets.HUB_DOCKER_TOKEN}}" | docker login -u "${{secrets.HUB_DOCKER_NAME}}" --password-stdin

      # 백엔드 이미지 생성 -> 허브(레퍼지토리 푸시)
      - name:  백엔드 이미지 생성
        run: |
          docker build -t park0628/demo_backend ./backend
          docker push park0628/demo_backend

      # 프론트 이미지 생성 _> 허브 푸시
      - name:  백엔드 이미지 생성
        run: |
          docker build -t park0628/demo_frontend ./frontend
          docker push park0628/demo_frontend

      # ec2 서버로 필요 파일 업로드 (YML, nginx/*.conf)
      - name: EC2 서버로 필요 파일 업로드
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME }}
          key: ${{secrets.EC2_KEY}}
          source: |
            docker-compose.yml,
            ./nginx/default.conf
          target: /home/ubuntu



  deploy:
       runs-on: ubuntu-latest
# 해당 잡이 진행 될려면 사전에 반드시 다른 잡이 선행되야 한다
       needs: docker-cicd
       steps:
        - name: ec2에 SSH 접속 -> 도커 컴포즈 가동 -> 서비스 세팅완료
          uses: appleboy/ssh-action@v1.1.0
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_KEY }}   
            script_stop: true
            
            script: |
              sudo docker compose down
              sudo docker compose up -d